[2024-09-04 14:38:08,155] MacBook-Pro/INFO/root: Waiting for workers to be ready, 0 of 10 connected
[2024-09-04 14:38:08,680] MacBook-Pro/INFO/locust.runners: Worker MacBook-Pro.local_5e1a1fb6421f4062872be26a97274215 (index 0) reported as ready. 1 workers connected.
[2024-09-04 14:38:08,682] MacBook-Pro/INFO/locust.runners: Worker MacBook-Pro.local_437237e025f647d8a0ea1b4eb5c816c3 (index 1) reported as ready. 2 workers connected.
[2024-09-04 14:38:08,685] MacBook-Pro/INFO/locust.main: Starting Locust 2.31.4
[2024-09-04 14:38:08,687] MacBook-Pro/INFO/locust.main: Starting Locust 2.31.4
[2024-09-04 14:38:08,688] MacBook-Pro/INFO/locust.runners: Worker MacBook-Pro.local_23cc04ecc8d54059928d4974add2ad87 (index 2) reported as ready. 3 workers connected.
[2024-09-04 14:38:08,691] MacBook-Pro/INFO/locust.runners: Worker MacBook-Pro.local_db6f482ef85e4d95ae981da2427c80c2 (index 3) reported as ready. 4 workers connected.
[2024-09-04 14:38:08,692] MacBook-Pro/INFO/locust.main: Starting Locust 2.31.4
[2024-09-04 14:38:08,694] MacBook-Pro/INFO/locust.main: Starting Locust 2.31.4
[2024-09-04 14:38:08,697] MacBook-Pro/INFO/locust.runners: Worker MacBook-Pro.local_10e036a7af7d43848d478b2772d2a46a (index 4) reported as ready. 5 workers connected.
[2024-09-04 14:38:08,698] MacBook-Pro/INFO/locust.runners: Worker MacBook-Pro.local_210aefce10b643aeb5952df9a81aa4d9 (index 5) reported as ready. 6 workers connected.
[2024-09-04 14:38:08,700] MacBook-Pro/INFO/locust.main: Starting Locust 2.31.4
[2024-09-04 14:38:08,698] MacBook-Pro/INFO/locust.main: Starting Locust 2.31.4
[2024-09-04 14:38:08,704] MacBook-Pro/INFO/locust.main: Starting Locust 2.31.4
[2024-09-04 14:38:08,704] MacBook-Pro/INFO/locust.runners: Worker MacBook-Pro.local_b97c65328e0a40be85650b7981ffde96 (index 6) reported as ready. 7 workers connected.
[2024-09-04 14:38:08,710] MacBook-Pro/INFO/locust.runners: Worker MacBook-Pro.local_1aea1a2cf45149768411f64cf06f9d58 (index 7) reported as ready. 8 workers connected.
[2024-09-04 14:38:08,711] MacBook-Pro/INFO/locust.main: Starting Locust 2.31.4
[2024-09-04 14:38:08,713] MacBook-Pro/INFO/locust.runners: Worker MacBook-Pro.local_09be8f11f8714f3b920802351857bec8 (index 8) reported as ready. 9 workers connected.
[2024-09-04 14:38:08,714] MacBook-Pro/INFO/locust.main: Starting Locust 2.31.4
[2024-09-04 14:38:08,718] MacBook-Pro/INFO/locust.runners: Worker MacBook-Pro.local_7c09ed50996f4987b6b00b356c88048d (index 9) reported as ready. 10 workers connected.
[2024-09-04 14:38:08,718] MacBook-Pro/INFO/locust.main: Starting Locust 2.31.4
[2024-09-04 14:38:09,156] MacBook-Pro/INFO/locust.main: No run time limit set, use CTRL+C to interrupt
[2024-09-04 14:38:09,158] MacBook-Pro/INFO/locust.main: Starting Locust 2.31.4
[2024-09-04 14:38:09,159] MacBook-Pro/INFO/locust.runners: Sending spawn jobs of 10 users at 10.00 spawn rate to 10 ready workers
[2024-09-04 14:38:09,271] MacBook-Pro/INFO/locust.runners: All users spawned: {"QianfanLLMLoadUser": 10} (10 total users)
[2024-09-04 14:38:09,780] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:09,783] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:09,803] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:09,803] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:09,848] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:09,852] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:09,905] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:09,910] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:09,916] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:09,919] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:09,970] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:09,982] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,019] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,027] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,044] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,058] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,060] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,103] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,123] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,131] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,153] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,162] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,185] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,186] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,199] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,226] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,236] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,269] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,293] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,295] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,311] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,326] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,344] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,344] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,352] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,360] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,387] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,399] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,421] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,427] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,427] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,448] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,457] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,465] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,521] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,526] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,533] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,543] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,549] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,562] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,581] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,587] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,589] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,595] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,601] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,643] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,649] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,662] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,670] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,707] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,737] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,755] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,762] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,766] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,785] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,804] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,823] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,850] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,876] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,885] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,899] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,903] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,936] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,940] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,946] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,999] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:10,999] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:11,000] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:11,018] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:11,022] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:11,041] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:11,046] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:11,058] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:11,064] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:11,123] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:11,123] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:11,135] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:11,153] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:11,371] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:12,659] MacBook-Pro/ERROR/locust.user.task: Object of type _GenericAlias is not JSON serializable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 340, in run
    self.execute_next_task()
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 373, in execute_next_task
    self.execute_task(self._task_queue.popleft())
  File "/opt/anaconda3/envs/xn/lib/python3.11/site-packages/locust/user/task.py", line 490, in execute_task
    task(self.user)
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 698, in mytask
    self.client.qianfan_request(
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 134, in qianfan_request
    request_meta = self._request_internal(context=context, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jianruitian/Documents/GitHub/bce-qianfan-sdk/python/qianfan/dataset/stress_test/qianfan_llm_load.py", line 352, in _request_internal
    res = json.dumps(res,ensure_ascii=False)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/xn/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type _GenericAlias is not JSON serializable

[2024-09-04 14:38:12,662] MacBook-Pro.local/WARNING/yame.runner: Distributor[distributor] StopIteration occurs 10 times, and 10 users have been spawned.
[2024-09-04 14:38:12,665] MacBook-Pro/INFO/locust.runners: Got quit message from master, shutting down...
[2024-09-04 14:38:12,665] MacBook-Pro/INFO/locust.runners: Got quit message from master, shutting down...
[2024-09-04 14:38:12,665] MacBook-Pro/INFO/locust.runners: Got quit message from master, shutting down...
[2024-09-04 14:38:12,665] MacBook-Pro/INFO/locust.runners: Got quit message from master, shutting down...
[2024-09-04 14:38:12,665] MacBook-Pro/INFO/locust.runners: Got quit message from master, shutting down...
[2024-09-04 14:38:12,665] MacBook-Pro/INFO/locust.runners: Got quit message from master, shutting down...
[2024-09-04 14:38:12,666] MacBook-Pro/INFO/locust.runners: Got quit message from master, shutting down...
[2024-09-04 14:38:12,666] MacBook-Pro/INFO/locust.runners: Got quit message from master, shutting down...
[2024-09-04 14:38:12,669] MacBook-Pro/INFO/locust.runners: Got quit message from master, shutting down...
[2024-09-04 14:38:12,672] MacBook-Pro/INFO/locust.runners: Got quit message from master, shutting down...
[2024-09-04 14:38:12,742] MacBook-Pro/INFO/locust.main: Shutting down (exit code 0)
[2024-09-04 14:38:12,742] MacBook-Pro/INFO/locust.runners: Worker 'MacBook-Pro.local_db6f482ef85e4d95ae981da2427c80c2' (index 3) quit. 0 workers ready.
[2024-09-04 14:38:12,749] MacBook-Pro/INFO/locust.main: Shutting down (exit code 0)
[2024-09-04 14:38:12,750] MacBook-Pro/INFO/locust.main: Shutting down (exit code 0)
[2024-09-04 14:38:12,751] MacBook-Pro/INFO/locust.runners: Worker 'MacBook-Pro.local_7c09ed50996f4987b6b00b356c88048d' (index 9) quit. 0 workers ready.
[2024-09-04 14:38:12,753] MacBook-Pro/INFO/locust.main: Shutting down (exit code 0)
[2024-09-04 14:38:12,753] MacBook-Pro/INFO/locust.runners: Worker 'MacBook-Pro.local_10e036a7af7d43848d478b2772d2a46a' (index 4) quit. 0 workers ready.
[2024-09-04 14:38:12,753] MacBook-Pro/INFO/locust.main: Shutting down (exit code 0)
[2024-09-04 14:38:12,755] MacBook-Pro/INFO/locust.main: Shutting down (exit code 0)
[2024-09-04 14:38:12,755] MacBook-Pro/INFO/locust.main: Shutting down (exit code 0)
[2024-09-04 14:38:12,756] MacBook-Pro/INFO/locust.runners: Worker 'MacBook-Pro.local_210aefce10b643aeb5952df9a81aa4d9' (index 5) quit. 0 workers ready.
[2024-09-04 14:38:12,757] MacBook-Pro/INFO/locust.runners: Worker 'MacBook-Pro.local_437237e025f647d8a0ea1b4eb5c816c3' (index 1) quit. 0 workers ready.
[2024-09-04 14:38:12,758] MacBook-Pro/INFO/locust.runners: Worker 'MacBook-Pro.local_b97c65328e0a40be85650b7981ffde96' (index 6) quit. 0 workers ready.
[2024-09-04 14:38:12,758] MacBook-Pro/INFO/locust.main: Shutting down (exit code 0)
[2024-09-04 14:38:12,758] MacBook-Pro/INFO/locust.runners: Worker 'MacBook-Pro.local_23cc04ecc8d54059928d4974add2ad87' (index 2) quit. 0 workers ready.
[2024-09-04 14:38:12,759] MacBook-Pro/INFO/locust.runners: Worker 'MacBook-Pro.local_5e1a1fb6421f4062872be26a97274215' (index 0) quit. 0 workers ready.
[2024-09-04 14:38:12,760] MacBook-Pro/INFO/locust.main: Shutting down (exit code 0)
[2024-09-04 14:38:12,760] MacBook-Pro/INFO/locust.runners: Worker 'MacBook-Pro.local_09be8f11f8714f3b920802351857bec8' (index 8) quit. 0 workers ready.
[2024-09-04 14:38:12,766] MacBook-Pro/INFO/locust.main: Shutting down (exit code 0)
[2024-09-04 14:38:12,766] MacBook-Pro/INFO/locust.runners: Worker 'MacBook-Pro.local_1aea1a2cf45149768411f64cf06f9d58' (index 7) quit. 0 workers ready.
[2024-09-04 14:38:12,766] MacBook-Pro/INFO/locust.runners: The last worker quit, stopping test.
[2024-09-04 14:38:13,250] MacBook-Pro/INFO/locust.main: writing html report to file: record/20240904T143808Z/round-user_num_10/report_user_num_10.html
[2024-09-04 14:38:13,755] MacBook-Pro/INFO/locust.main: Shutting down (exit code 1)
